repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
- repo: https://github.com/asottile/yesqa
  rev: f2ae90cf9e1661ade79d0881186ce4fd7ba6ee79  # frozen: v1.5.0
  hooks:
  - id: yesqa
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: 1683a63d850e065495c05b771e4a20db010a58e7  # frozen: v0.3.1
  hooks:
  - id: absolufy-imports
- repo: https://github.com/PyCQA/isort
  rev: c8ab4a5b21bac924d106e3103dd7c979fdd0f9bc  # frozen: 6.0.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b  # frozen: 25.1.0
  hooks:
  - id: black
- repo: https://github.com/hukkin/docformatter
  rev: ab802050e6e96aaaf7f917fcbc333bb74e2e57f7  # frozen: v1.4.2
  hooks:
  - id: docformatter
- repo: https://github.com/PyCQA/flake8
  rev: 4b5e89b4b108a6c1a000c591d334a99a80d34c7b  # frozen: 7.2.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/pre-commit/pre-commit
  rev: aa48766b888990e7b118d12cf757109d96e65a7e  # frozen: v4.2.0
  hooks:
  - id: validate_manifest
